obj-$(CONFIG_NAND_SUNXI_BLK) += nand_sunxi_blk.o
nand_sunxi_blk-y := ./nand_drv/nand_for_uboot.o \
		   ./nand_drv/nand_osal_uboot.o 		\
		   ./nand_drv/nand_fspart.o 			\
		   ./src/format/nand_format.o			\
		   ./src/logic/bad_manage.o				\
		   ./src/logic/logic_cache.o			\
		   ./src/logic/logic_ctl.o				\
		   ./src/logic/mapping.o				\
		   ./src/logic/mapping_base.o			\
		   ./src/logic/merge.o					\
		   ./src/logic/read_reclaim.o			\
		   ./src/logic/wear_levelling.o			\
		   ./src/nfc/nfc_r.o					\
		   ./src/nfc/nfc_w.o					\
		   ./src/physic/nand_phy.o				\
		   ./src/physic/nand_simple_r.o			\
		   ./src/physic/nand_simple_w.o			\
		   ./src/scan/nand_id.o					\
           ./src/logic/mbr.o                    \
		   ./src/scan/nand_scan.o
